### ISSUE TITLE
复现报错。

### ISSUE THREAD

**Issue by Ruyi520** [zbxytx/Multi_feature_MER#2]
您好，我是一名微表情研究方向的学生，在对您的代码复现的过程中，遇到了一个难以解决的问题：在Classification_and_evaluation.py 中第41行，出现这样的错误
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
在网上找了一些方法仍无法解决，期待您的帮助。

temporal interpolate
feature extraction
evaluation
D:/New folder/xiangmu/Multi_feature_MER-master/main.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Estimated Emotion'][i] = 'positive'
D:/New folder/xiangmu/Multi_feature_MER-master/main.py:64: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Estimated Emotion'][i] = 'others'
D:\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
LBP_features:
kernel= linear split= loso average= macro
D:\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
Traceback (most recent call last):
  File "D:/New folder/xiangmu/Multi_feature_MER-master/main.py", line 156, in <module>
    ce.get_best_average(LBP_feature, labels, sub_list, kernel='linear', split='loso', average='macro')
  File "D:\New folder\xiangmu\Multi_feature_MER-master\Classification_and_evaluation.py", line 97, in get_best_average
    C=C, split=split, average=average)
  File "D:\New folder\xiangmu\Multi_feature_MER-master\Classification_and_evaluation.py", line 41, in avg_score
    result = classifier.predict(test_data)
  File "D:\Anaconda\envs\tfg\lib\site-packages\sklearn\svm\_base.py", line 594, in predict
    y = super().predict(X)
  File "D:\Anaconda\envs\tfg\lib\site-packages\sklearn\svm\_base.py", line 315, in predict
    X = self._validate_for_predict(X)
  File "D:\Anaconda\envs\tfg\lib\site-packages\sklearn\svm\_base.py", line 447, in _validate_for_predict
    accept_large_sparse=False)
  File "D:\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py", line 556, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by wangzhenxing2** [comment]
这可能是数据划分的问题，划分后有个batch_size只有一张图片，二维数组就变为一维数组了，而代码要求是二维数组；所以你就按提示把一维数组reshape成二维数组就行了，意思就是这么个意思

**Comment by Ruyi520** [comment]
非常感谢，确实是数据划分的问题，可能是我比较愚钝，还是没有找到reshape的正确位置，
不过，我通过去掉def data_split()模块，改为调用from sklearn.model_selection import train_test_split实现了这一功能，再次感谢您的回复！！！！

**Comment by Novices-psy** [comment]
您好，我是一名做微表情识别的学生，在运行您代码过程中，按照您的要求，配置了相关环境，python3.6.10，pandas1.0.1，numpy1.19.0，运行后报错，main.py里第17行 ，File "F:\Anaconda\envs\myenv\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'Subject'，提示没有Subject属性，百度后说是更换pandas版本问题，我回退到0.25.0后，read_excel方法却没有了，我在网上搜索想更换另一种方法替代subject，但pandas的手册，也没找到subject的属性解释，请问这种情况，怎样才能解决，期待您的答复

**Comment by Novices-psy** [comment]
> 非常感谢，确实是数据划分的问题，可能是我比较愚拙，还是没有找到reshape的正确位置，
> 不过，我通过去了def data_split（）模块，从sklearn.model_selection导入import train_test_split实现了这一功能，再次感谢您的回复！！！！

您好，请问您完成了代码复现吗？本人也在复现中遇到一些困难，想向您咨询相关问题，添加您好友，询问相关问题吗

**Comment by Ruyi520** [comment]
> > 非常感谢，确实是数据划分的问题，可能是我比较愚拙，还是没有找到reshape的正确位置，
> > 不过，我通过去了def data_split（）模块，从sklearn.model_selection导入import train_test_split实现了这一功能，再次感谢您的回复！！！！
> 
> 您好，请问您完成了代码复现吗？本人也在复现中遇到一些困难，想向您咨询相关问题，添加您好友，询问相关问题吗

博主分享的代码，没有太多的问题，我复现的时候只碰到了那一处，严格按照要求配置运行环境就好了。

**Comment by SLENDER-G** [comment]
您好，这个casme2可以分享一下吗这个文件夹没找到

**Comment by cloudlyyyyyy** [comment]
您好，我也是微表情研究方向的一名研一学生，请问可以互相交流吗，因为我的组只有我一个是这个方向的，如果您也觉得可以的话，可以添加我的扣扣：1181973936

**Comment by SLENDER-G** [comment]
不好意思，我现在不做这些东西了。当时做这个是为了本科的毕业设计糊弄了一下，估计帮不了你。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cloudlyyyyyy ***@***.***&gt;
发送时间: 2023年12月7日 15:14
收件人: zbxytx/Multi_feature_MER ***@***.***&gt;
抄送: wangshaolun ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2)





 
您好，我也是微表情研究方向的一名研一学生，请问可以互相交流吗，因为我的组只有我一个是这个方向的，如果您也觉得可以的话，可以添加我的扣扣：1181973936

**Comment by cloudlyyyyyy** [comment]
好滴没关系(๑&gt;ᴗ<๑)，不知道当时这篇有没有相关论文呀？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangshaolun ***@***.***&gt;
发送时间: 2023年12月7日 15:18
收件人: zbxytx/Multi_feature_MER ***@***.***&gt;
抄送: cloudlyyyyyy ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2)





 不好意思，我现在不做这些东西了。当时做这个是为了本科的毕业设计糊弄了一下，估计帮不了你。 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: cloudlyyyyyy ***@***.***&amp;gt; 
 发送时间: 2023年12月7日 15:14 
 收件人: zbxytx/Multi_feature_MER ***@***.***&amp;gt; 
 抄送: wangshaolun ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2) 
 
 
 
 
 
   
 您好，我也是微表情研究方向的一名研一学生，请问可以互相交流吗，因为我的组只有我一个是这个方向的，如果您也觉得可以的话，可以添加我的扣扣：1181973936

**Comment by yyyyn4** [comment]
> 不好意思，我现在不做这些东西了。当时做这个是为了本科的毕业设计糊弄了一下，估计帮不了你。 发自我的iPhone
> [...](#)
> ------------------ 原始邮件 ------------------ 发件人: cloudlyyyyyy ***@***.***&gt; 发送时间: 2023年12月7日 15:14 收件人: zbxytx/Multi_feature_MER ***@***.***&gt; 抄送: wangshaolun ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2) 您好，我也是微表情研究方向的一名研一学生，请问可以互相交流吗，因为我的组只有我一个是这个方向的，如果您也觉得可以的话，可以添加我的扣扣：1181973936 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，我想请问一下有相关的论文吗，

**Comment by cloudlyyyyyy** [comment]
好的 谢谢啦🌹



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yyyyn4 ***@***.***&gt;
发送时间: 2024年3月24日 21:08
收件人: zbxytx/Multi_feature_MER ***@***.***&gt;
抄送: cloudlyyyyyy ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2)





  
不好意思，我现在不做这些东西了。当时做这个是为了本科的毕业设计糊弄了一下，估计帮不了你。 发自我的iPhone
 ...
 ------------------ 原始邮件 ------------------ 发件人: cloudlyyyyyy @.&gt; 发送时间: 2023年12月7日 15:14 收件人: zbxytx/Multi_feature_MER @.&gt; 抄送: wangshaolun @.&gt;, Comment @.&gt; 主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2) 您好，我也是微表情研究方向的一名研一学生，请问可以互相交流吗，因为我的组只有我一个是这个方向的，如果您也觉得可以的话，可以添加我的扣扣：1181973936 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
您好，我想请问一下有相关的论文吗，

**Comment by yyyyn4** [comment]
> > > 非常感谢，确实是数据划分的问题，可能是我比较愚拙，还是没有找到reshape的正确位置，
> > > 不过，我通过去了def data_split（）模块，从sklearn.model_selection导入import train_test_split实现了这一功能，再次感谢您的回复！！！！
> > 
> > 
> > 您好，请问您完成了代码复现吗？本人也在复现中遇到一些困难，想向您咨询相关问题，添加您好友，询问相关问题吗
> 
> 博主分享的代码，没有太多的问题，我复现的时候只碰到了那一处，严格按照要求配置运行环境就好了。


> 您好，这个casme2可以分享一下吗这个文件夹没找到

您好，请问您有这个casme2文件夹吗

**Comment by Novices-psy** [comment]
版权原因，你需要自己写邮件给傅小兰博士，申请casme2数据集使用许可，说明具体用途，具体申请文件书在这里http://casme.psych.ac.cn/casme/c2，







                       
Original Email
                       
                     

Sender:"yyyyn4"< ***@***.*** &gt;;

Sent Time:2024/3/28 10:22

To:"zbxytx/Multi_feature_MER"< ***@***.*** &gt;;

Cc recipient:"Novices-psy"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2)




    
非常感谢，确实是数据划分的问题，可能是我比较愚拙，还是没有找到reshape的正确位置，
 不过，我通过去了def data_split（）模块，从sklearn.model_selection导入import train_test_split实现了这一功能，再次感谢您的回复！！！！
  
您好，请问您完成了代码复现吗？本人也在复现中遇到一些困难，想向您咨询相关问题，添加您好友，询问相关问题吗
  
博主分享的代码，没有太多的问题，我复现的时候只碰到了那一处，严格按照要求配置运行环境就好了。
   
您好，这个casme2可以分享一下吗这个文件夹没找到
  
您好，请问您有这个casme2文件夹吗

**Comment by yyyyn4** [comment]
> 您好，我是一名微表情研究方向的学生，在对您的代码复现的过程中，遇到了一个难以解决的问题：在Classification_and_evaluation.py 中第41行，出现这样的错误 ValueError： Expected 2D array， got 1D array instead： array=[].如果数据具有单个特征，则使用 array.reshape（-1， 1） 或 array.reshape（1， -1） （如果数据包含单个样本）来重塑数据。 在网上找了一些方法仍无法解决，期待您的帮助。
> 
> 时态插值特征提取评估 D：/New folder/xiangmu/Multi_feature_MER-master/main.py：73：SettingWithCopyWarning：尝试在 DataFrame 中切片的副本上设置值
> 
> 请参阅文档中的警告： https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy df['估计的情绪'][i] = 'positive' D：/New folder/xiangmu/Multi_feature_MER-master/main.py：64： SettingWithCopyWarning：正在尝试对 DataFrame 中切片的副本设置值
> 
> 请参阅文档中的警告： https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy df['估计的情绪'][i] = 'others' D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760： DataConversionWarning： 当预期是一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760：DataConversionWarning：当需要一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760：DataConversionWarning：当需要一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） LBP_features：kernel= linear split= loso average= macro D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760：DataConversionWarning：当预期是一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） 回溯（最近一次调用最后）：文件“D：/New folder/xiangmu/Multi_feature_MER-master/main.py”，第 156 行，在 ce.get_best_average（LBP_feature， labels， sub_list， kernel='linear'， split='loso'， average='macro'） 文件“D：\New folder\xiangmu\Multi_feature_MER-master\Classification_and_evaluation.py”，第 97 行，在 get_best_average C=C， split=split， average=average） 文件“D：\New folder\xiangmu\Multi_feature_MER-master\Classification_and_evaluation.py”，第 41 行，在 avg_score result = classifier.predict（test_data） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\svm_base.py”，第 594 行，在 predict y = super（）.predict（X） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\svm_base.py”，第 315 行，在 predict X = self._validate_for_predict（X） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\svm_base.py”，第 447 行，_validate_for_predict accept_large_sparse=False） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py”，第 556 行，check_array“如果它包含单个样本”。format（array）） ValueError：预期的 2D 数组，得到 1D 数组：array=[]。如果数据具有单个特征，则使用 array.reshape（-1， 1） 或 array.reshape（1， -1） （如果数据包含单个样本）来重塑数据。

您好，我是一名做微表情识别的学生，在复现代码的过程中遇到了些问题，我找不到UniformLBP8.txt文件。请您给我指点一下，万分感谢！

**Comment by cloudlyyyyyy** [comment]
您好我也是微表情识别方向的学生，不知道您是不是发错消息了 方便加个联系方式可以平时交流一下嘛 我的微信：hcy021502hcy
有关于代码中光流的问题我想咨询一下😊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yyyyn4 ***@***.***&gt;
发送时间: 2024年3月29日 16:12
收件人: zbxytx/Multi_feature_MER ***@***.***&gt;
抄送: cloudlyyyyyy ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2)





  
您好，我是一名微表情研究方向的学生，在对您的代码复现的过程中，遇到了一个难以解决的问题：在Classification_and_evaluation.py 中第41行，出现这样的错误 ValueError： Expected 2D array， got 1D array instead： array=[].如果数据具有单个特征，则使用 array.reshape（-1， 1） 或 array.reshape（1， -1） （如果数据包含单个样本）来重塑数据。 在网上找了一些方法仍无法解决，期待您的帮助。
 
时态插值特征提取评估 D：/New folder/xiangmu/Multi_feature_MER-master/main.py：73：SettingWithCopyWarning：尝试在 DataFrame 中切片的副本上设置值
 
请参阅文档中的警告： https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy df['估计的情绪'][i] = 'positive' D：/New folder/xiangmu/Multi_feature_MER-master/main.py：64： SettingWithCopyWarning：正在尝试对 DataFrame 中切片的副本设置值
 
请参阅文档中的警告： https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy df['估计的情绪'][i] = 'others' D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760： DataConversionWarning： 当预期是一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760：DataConversionWarning：当需要一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760：DataConversionWarning：当需要一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） LBP_features：kernel= linear split= loso average= macro D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py:760：DataConversionWarning：当预期是一维数组时，传递了列向量 y。请将 y 的形状更改为 （n_samples， ），例如使用 ravel（）。 y = column_or_1d（y， warn=True） 回溯（最近一次调用最后）：文件“D：/New folder/xiangmu/Multi_feature_MER-master/main.py”，第 156 行，在 ce.get_best_average（LBP_feature， labels， sub_list， kernel='linear'， split='loso'， average='macro'） 文件“D：\New folder\xiangmu\Multi_feature_MER-master\Classification_and_evaluation.py”，第 97 行，在 get_best_average C=C， split=split， average=average） 文件“D：\New folder\xiangmu\Multi_feature_MER-master\Classification_and_evaluation.py”，第 41 行，在 avg_score result = classifier.predict（test_data） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\svm_base.py”，第 594 行，在 predict y = super（）.predict（X） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\svm_base.py”，第 315 行，在 predict X = self._validate_for_predict（X） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\svm_base.py”，第 447 行，_validate_for_predict accept_large_sparse=False） 文件“D：\Anaconda\envs\tfg\lib\site-packages\sklearn\utils\validation.py”，第 556 行，check_array“如果它包含单个样本”。format（array）） ValueError：预期的 2D 数组，得到 1D 数组：array=[]。如果数据具有单个特征，则使用 array.reshape（-1， 1） 或 array.reshape（1， -1） （如果数据包含单个样本）来重塑数据。
  
您好，我是一名做微表情识别的学生，在复现代码的过程中遇到了些问题，我找不到UniformLBP8.txt文件。请您给我指点一下，万分感谢！

**Comment by cloudlyyyyyy** [comment]
数据集文件夹我有 可以加我联系方式





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yyyyn4 ***@***.***&gt;
发送时间: 2024年3月28日 10:22
收件人: zbxytx/Multi_feature_MER ***@***.***&gt;
抄送: cloudlyyyyyy ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2)





    
非常感谢，确实是数据划分的问题，可能是我比较愚拙，还是没有找到reshape的正确位置，
 不过，我通过去了def data_split（）模块，从sklearn.model_selection导入import train_test_split实现了这一功能，再次感谢您的回复！！！！
  
您好，请问您完成了代码复现吗？本人也在复现中遇到一些困难，想向您咨询相关问题，添加您好友，询问相关问题吗
  
博主分享的代码，没有太多的问题，我复现的时候只碰到了那一处，严格按照要求配置运行环境就好了。
   
您好，这个casme2可以分享一下吗这个文件夹没找到
  
您好，请问您有这个casme2文件夹吗

**Comment by yyyyn4** [comment]
您好，这是我的微信：j06151108


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月29日(周五) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2)




 数据集文件夹我有 可以加我联系方式 
 
 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: yyyyn4 ***@***.***&amp;gt; 
 发送时间: 2024年3月28日 10:22 
 收件人: zbxytx/Multi_feature_MER ***@***.***&amp;gt; 
 抄送: cloudlyyyyyy ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [zbxytx/Multi_feature_MER] 复现报错。 (#2) 
 
 
 
 
 
      
 非常感谢，确实是数据划分的问题，可能是我比较愚拙，还是没有找到reshape的正确位置， 
  不过，我通过去了def data_split（）模块，从sklearn.model_selection导入import train_test_split实现了这一功能，再次感谢您的回复！！！！ 
    
 您好，请问您完成了代码复现吗？本人也在复现中遇到一些困难，想向您咨询相关问题，添加您好友，询问相关问题吗 
    
 博主分享的代码，没有太多的问题，我复现的时候只碰到了那一处，严格按照要求配置运行环境就好了。 
     
 您好，这个casme2可以分享一下吗这个文件夹没找到 
    
 您好，请问您有这个casme2文件夹吗
